headless: false
username: ${MYRTA_USERNAME}
password: ${MYRTA_PASSWORD}
have_booking: false
selenium_driver_url: http://localhost:57908
selenium_element_timout: 20000
selenium_element_polling: 100
retries: 4
scrape_refresh_time_min: 120
locations:
- '621'
- '17'
- '96'
- '241'
- '63'
- '35'
- '601'
- '37'
- '112'
date_filter_start: 2026-02-01
date_filter_end: 2026-09-30
alerts:
- location_id: '621'
  location_name: North Rocks
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '17'
  location_name: Albury
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '96'
  location_name: Ryde
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '241'
  location_name: Silverwater
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '63'
  location_name: Hornsby
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '35'
  location_name: Castle Hill
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '601'
  location_name: Auburn PCYC
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '37'
  location_name: Chatswood
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
- location_id: '112'
  location_name: Auburn
  enabled: true
  months:
  - 3
  - 4
  - 5
  - 6
alerts_enabled: true
auto_scrape_enabled: false
auto_scrape_interval_hours: 1
parallel_workers: 3
